[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sph-cli"
path = "src/main.rs"

[dependencies]
sph = { path = "../sph" }
image = "0.24"
clap = { version = "4.0", features = ["derive"] }
pollster = "0.3"