name: Deploy Site

on:
  push:
    branches: ["**"]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Vite site
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages (prod)
        if: github.ref == 'refs/heads/main'
        run: wrangler pages deploy dist --project-name=sph-prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Pages (dev)
        if: github.ref != 'refs/heads/main'
        run: wrangler pages deploy dist --project-name=sph-dev --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
